### ISSUE TITLE
publish version 0.2.2 on crates.io

### ISSUE THREAD

**Issue by Luap99** [rust-netlink/netlink-packet-wireguard#4]
commit https://github.com/rust-netlink/netlink-packet-wireguard/commit/9b29307e5cab2b370ceb09b419e2b0887330556e bump the version to 2.2.0 but this version was never pushed to crates.io.
It would be nice to keep them in sync so we do not have to specify the git repo in cargo.toml to use the latest version.

@cathay4t PTAL

**Comment by cathay4t** [comment]
@Luap99 Sorry for the long wait. I got compiling failure on example codes, let me fix it and release it.

Update: Fixed in #5

**Comment by cathay4t** [comment]
@little-dude Can you grant me the permission in crates.io for `netlink-packet-wireguard`?

**Comment by cathay4t** [comment]
@little-dude ^

**Comment by cathay4t** [comment]
I got the permission and publishsed netlink-packet-wireguard 0.2.3 to crates.io

**Comment by Luap99** [comment]
thanks
